JACR__20241103/Controllers/EmpleadoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JACR__20241103.Models;

namespace JACR__20241103.Controllers
{
    public class EmpleadoesController : Controller
    {
        private readonly JCT20241103Context _context;

        public EmpleadoesController(JCT20241103Context context)
        {
            _context = context;
        }

        // GET: Empleadoes
        public async Task<IActionResult> Index()
        {
              return _context.Empleados != null ? 
                          View(await _context.Empleados.ToListAsync()) :
                          Problem("Entity set 'JCT20241103Context.Empleados'  is null.");
        }

        // GET: Empleadoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .Include(e => e.ReferenciasPersonales)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleadoes/Create
        public IActionResult Create()
        {
            var empleado = new Empleado(); // o cualquier lógica para crear un nuevo empleado
            return View(empleado);
        }


        // POST: Empleadoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Edad,Departamento,Salario")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleadoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Empleados == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleadoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Edad,Departamento,Salario")] Empleado empleado)
        {
            if (id != empleado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleadoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Empleados == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Empleados == null)
            {
                return Problem("Entity set 'JCT20241103Context.Empleados'  is null.");
            }
            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado != null)
            {
                _context.Empleados.Remove(empleado);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
          return (_context.Empleados?.Any(e => e.Id == id)).GetValueOrDefault();
        }

    }
}

JACR__20241103/Controllers/ReferenciasPersonalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JACR__20241103.Models;

namespace JACR__20241103.Controllers

    {
        public class ReferenciasPersonalesController : Controller
        {
            private readonly JCT20241103Context _context;

            public ReferenciasPersonalesController(JCT20241103Context context)
            {
                _context = context;
            }
        // GET: ReferenciasPersonales/Create
        public IActionResult Create(int empleadoId)
        {
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Nombre", empleadoId);
            return View();
        }



        // POST: ReferenciasPersonales/Create
        [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create([Bind("Id,EmpleadoId,Nombre,Apellido,Telefono")] ReferenciasPersonale referenciaPersonal)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(referenciaPersonal);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "Empleadoes", new { id = referenciaPersonal.EmpleadoId });
                }
                return View(referenciaPersonal);
            }

            // GET: ReferenciasPersonales/Edit/5
            public async Task<IActionResult> Edit(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var referenciaPersonal = await _context.ReferenciasPersonales.FindAsync(id);
                if (referenciaPersonal == null)
                {
                    return NotFound();
                }
                return View(referenciaPersonal);
            }

            // POST: ReferenciasPersonales/Edit/5
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("Id,EmpleadoId,Nombre,Apellido,Telefono")] ReferenciasPersonale referenciaPersonal)
            {
                if (id != referenciaPersonal.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(referenciaPersonal);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ReferenciaPersonalExists(referenciaPersonal.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction("Details", "Empleados", new { id = referenciaPersonal.EmpleadoId });
                }
                return View(referenciaPersonal);
            }

            // GET: ReferenciasPersonales/Delete/5
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var referenciaPersonal = await _context.ReferenciasPersonales
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (referenciaPersonal == null)
                {
                    return NotFound();
                }

                return View(referenciaPersonal);
            }

            // POST: ReferenciasPersonales/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                var referenciaPersonal = await _context.ReferenciasPersonales.FindAsync(id);
                _context.ReferenciasPersonales.Remove(referenciaPersonal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool ReferenciaPersonalExists(int id)
            {
                return _context.ReferenciasPersonales.Any(e => e.Id == id);
            }
        }
    }

JACR__20241103/Views/Empleadoes/Create.cshtml
@model JACR__20241103.Models.Empleado

@{
    ViewData["Title"] = "Create";
}
<style>
    body {
        background-color: lightblue;
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
<div class="container">
    <h1 class="mt-4">Crear Empleado</h1>

    <div class="mt-4">
        <h4>Datos del Empleado</h4>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <label for="Nombre" class="col-sm-2 col-form-label">Nombre:</label>
                <div class="col-sm-10">
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label for="Apellido" class="col-sm-2 col-form-label">Apellido:</label>
                <div class="col-sm-10">
                    <input asp-for="Apellido" class="form-control" />
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label for="Edad" class="col-sm-2 col-form-label">Edad:</label>
                <div class="col-sm-10">
                    <input asp-for="Edad" class="form-control" />
                    <span asp-validation-for="Edad" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label for="Departamento" class="col-sm-2 col-form-label">Departamento:</label>
                <div class="col-sm-10">
                    <input asp-for="Departamento" class="form-control" />
                    <span asp-validation-for="Departamento" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label for="Salario" class="col-sm-2 col-form-label">Salario:</label>
                <div class="col-sm-10">
                    <input asp-for="Salario" class="form-control" />
                    <span asp-validation-for="Salario" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>

    <div class="mt-4">
        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
                <a asp-action="Create" asp-controller="ReferenciasPersonales" asp-route-empleadoId="@Model.Id" class="btn btn-success">Agregar Referencia Personal</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

JACR__20241103/Views/Empleadoes/Delete.cshtml
@model JACR__20241103.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}
<style>
    body {
        background-color: lightblue;
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
<div class="container">
    <h1 class="mt-4">Eliminar Empleado</h1>

    <div class="mt-4">
        <h3>¿Estás seguro de que deseas eliminar este empleado?</h3>
        <hr />
        <h4>Detalles del Empleado:</h4>
        <dl class="row">
            <dt class="col-sm-4">Nombre:</dt>
            <dd class="col-sm-8">@Html.DisplayFor(model => model.Nombre)</dd>
            <dt class="col-sm-4">Apellido:</dt>
            <dd class="col-sm-8">@Html.DisplayFor(model => model.Apellido)</dd>
            <dt class="col-sm-4">Edad:</dt>
            <dd class="col-sm-8">@Html.DisplayFor(model => model.Edad)</dd>
            <dt class="col-sm-4">Departamento:</dt>
            <dd class="col-sm-8">@Html.DisplayFor(model => model.Departamento)</dd>
            <dt class="col-sm-4">Salario:</dt>
            <dd class="col-sm-8">@Html.DisplayFor(model => model.Salario)</dd>
        </dl>
    </div>

    <div class="mt-4">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
        </form>
    </div>
</div>

JACR__20241103/Views/Empleadoes/Details.cshtml
@model JACR__20241103.Models.Empleado

@{
    ViewData["Title"] = "Details";
}
<style>
    body {
        background-color: lightblue;
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<div class="container">
    <h1 class="mt-4">Detalles del Empleado</h1>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card" style=" background-color: lightblue;">
                <div class="card-body">
                    <h4 class="card-title">Empleado</h4>
                    <hr />
                    <dl class="row">
                        <dt class="col-sm-4">Nombre</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Nombre)</dd>
                        <dt class="col-sm-4">Apellido</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Apellido)</dd>
                        <dt class="col-sm-4">Edad</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Edad)</dd>
                        <dt class="col-sm-4">Departamento</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Departamento)</dd>
                        <dt class="col-sm-4">Salario</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Salario)</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-4">
        <h3>Referencias Personales</h3>
        @if (Model.ReferenciasPersonales != null && Model.ReferenciasPersonales.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Teléfono</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var referencia in Model.ReferenciasPersonales)
                    {
                        <tr>
                            <td>@referencia.Nombre</td>
                            <td>@referencia.Apellido</td>
                            <td>@referencia.Telefono</td>
                            <td>
                                <a asp-controller="ReferenciasPersonales" asp-action="Edit" asp-route-id="@referencia.Id" class="btn btn-sm btn-primary">Editar</a>
                                <a asp-controller="ReferenciasPersonales" asp-action="Delete" asp-route-id="@referencia.Id" class="btn btn-sm btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No hay referencias personales registradas para este empleado.</p>
        }
    </div>

    <div class="mt-4">
        <a asp-controller="ReferenciasPersonales" asp-action="Create" asp-route-empleadoId="@Model.Id" class="btn btn-primary">Agregar Referencia Personal</a>
        <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
    </div>
</div>

JACR__20241103/Views/Empleadoes/Edit.cshtml
@model JACR__20241103.Models.Empleado

@{
    ViewData["Title"] = "Edit";
}
<style>
    body {
        background-color:lightblue;
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<h1>Editar Empleado</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre</label>
                <input asp-for="Nombre" class="form-control" required />
                <span asp-validation-for="Nombre" class="text-danger"></span>
                <div class="invalid-feedback">Por favor, introduce un nombre.</div>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label">Apellido</label>
                <input asp-for="Apellido" class="form-control" required />
                <span asp-validation-for="Apellido" class="text-danger"></span>
                <div class="invalid-feedback">Por favor, introduce un apellido.</div>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label">Edad</label>
                <input asp-for="Edad" class="form-control" required />
                <span asp-validation-for="Edad" class="text-danger"></span>
                <div class="invalid-feedback">Por favor, introduce una edad válida.</div>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label">Departamento</label>
                <input asp-for="Departamento" class="form-control" required />
                <span asp-validation-for="Departamento" class="text-danger"></span>
                <div class="invalid-feedback">Por favor, introduce un departamento.</div>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label">Salario</label>
                <input asp-for="Salario" class="form-control" required />
                <span asp-validation-for="Salario" class="text-danger"></span>
                <div class="invalid-feedback">Por favor, introduce un salario válido.</div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

JACR__20241103/Views/Empleadoes/Index.cshtml
@model IEnumerable<JACR__20241103.Models.Empleado>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Empleados</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear Nuevo</a>
</p>
<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th>Departamento</th>
            <th>Salario</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.Apellido)</td>
                <td>@Html.DisplayFor(modelItem => item.Edad)</td>
                <td>@Html.DisplayFor(modelItem => item.Departamento)</td>
                <td>@Html.DisplayFor(modelItem => item.Salario)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-info">Detalles</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>